/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FirmwareUpgradeDeviceRequest =
  | {
      data: {
        data: number[];
      };
      method: "do_field_upgrade";
    }
  | {
      data: {};
      method: "progress";
    }
  | {
      data: {};
      method: "get_firmware_url";
    };
export type FirmwareUpgradeDeviceResponse =
  | {
      data: null;
      method: "do_field_upgrade";
    }
  | {
      data: number | null;
      method: "progress";
    }
  | {
      data: string | null;
      method: "get_firmware_url";
    };
export type FlexiCanRequest =
  | {
      data: {};
      method: "start_field_upgrade";
    }
  | {
      data: {
        msg: GrappleDeviceRequest;
      };
      method: "grapple";
    }
  | {
      data: {};
      method: "status";
    };
export type GrappleDeviceRequest =
  | {
      data: {};
      method: "blink";
    }
  | {
      data: {
        id: number;
      };
      method: "set_id";
    }
  | {
      data: {
        name: string;
      };
      method: "set_name";
    }
  | {
      data: {};
      method: "commit_to_eeprom";
    };
export type FlexiCanResponse =
  | {
      data: null;
      method: "start_field_upgrade";
    }
  | {
      data: GrappleDeviceResponse;
      method: "grapple";
    }
  | {
      data: FlexiCanStatus;
      method: "status";
    };
export type GrappleDeviceResponse =
  | {
      data: null;
      method: "blink";
    }
  | {
      data: null;
      method: "set_id";
    }
  | {
      data: null;
      method: "set_name";
    }
  | {
      data: null;
      method: "commit_to_eeprom";
    };
export type LaserCanRequest =
  | {
      data: {};
      method: "start_field_upgrade";
    }
  | {
      data: {
        mode: LaserCanRangingMode;
      };
      method: "set_range";
    }
  | {
      data: {
        roi: LaserCanRoi;
      };
      method: "set_roi";
    }
  | {
      data: {
        budget: LaserCanTimingBudget;
      };
      method: "set_timing_budget";
    }
  | {
      data: {
        msg: GrappleDeviceRequest;
      };
      method: "grapple";
    }
  | {
      data: {};
      method: "status";
    }
  | {
      data: {};
      method: "check_for_new_firmware";
    };
export type LaserCanRangingMode = "Short" | "Long";
export type LaserCanTimingBudget = "TB20ms" | "TB33ms" | "TB50ms" | "TB100ms";
export type LaserCanResponse =
  | {
      data: null;
      method: "start_field_upgrade";
    }
  | {
      data: null;
      method: "set_range";
    }
  | {
      data: null;
      method: "set_roi";
    }
  | {
      data: null;
      method: "set_timing_budget";
    }
  | {
      data: GrappleDeviceResponse;
      method: "grapple";
    }
  | {
      data: LaserCanStatus;
      method: "status";
    }
  | {
      data: LightReleaseResponse | null;
      method: "check_for_new_firmware";
    };
export type MitocandriaRequest =
  | {
      data: {};
      method: "start_field_upgrade";
    }
  | {
      data: {
        channel: MitocandriaSwitchableChannelRequest;
      };
      method: "set_switchable_channel";
    }
  | {
      data: {
        channel: MitocandriaAdjustableChannelRequest;
      };
      method: "set_adjustable_channel";
    }
  | {
      data: {};
      method: "calibrate_adjustable_channel";
    }
  | {
      data: {
        msg: GrappleDeviceRequest;
      };
      method: "grapple";
    }
  | {
      data: {};
      method: "status";
    }
  | {
      data: {};
      method: "check_for_new_firmware";
    };
export type MitocandriaResponse =
  | {
      data: null;
      method: "start_field_upgrade";
    }
  | {
      data: null;
      method: "set_switchable_channel";
    }
  | {
      data: null;
      method: "set_adjustable_channel";
    }
  | {
      data: null;
      method: "calibrate_adjustable_channel";
    }
  | {
      data: GrappleDeviceResponse;
      method: "grapple";
    }
  | {
      data: MitocandriaStatus;
      method: "status";
    }
  | {
      data: LightReleaseResponse | null;
      method: "check_for_new_firmware";
    };
export type MitocandriaChannelStatus =
  | {
      data: {
        current: number;
        enabled: boolean;
      };
      type: "Switchable";
    }
  | {
      data: {
        current: number;
      };
      type: "NonSwitchable";
    }
  | {
      data: {
        current: number;
        enabled: boolean;
        voltage: number;
        voltage_setpoint: number;
      };
      type: "Adjustable";
    };
export type OldVersionDeviceRequest =
  | {
      data: {};
      method: "start_field_upgrade";
    }
  | {
      data: {};
      method: "get_error";
    }
  | {
      data: {};
      method: "get_firmware_url";
    }
  | {
      data: {
        msg: GrappleDeviceRequest;
      };
      method: "grapple";
    };
export type OldVersionDeviceResponse =
  | {
      data: null;
      method: "start_field_upgrade";
    }
  | {
      data: string;
      method: "get_error";
    }
  | {
      data: string | null;
      method: "get_firmware_url";
    }
  | {
      data: GrappleDeviceResponse;
      method: "grapple";
    };
export type ProviderManagerRequest =
  | {
      data: {
        address: string;
      };
      method: "delete";
    }
  | {
      data: {
        address: string;
        msg: WrappedDeviceProviderRequest;
      };
      method: "provider";
    }
  | {
      data: {};
      method: "providers";
    };
export type WrappedDeviceProviderRequest =
  | {
      data: {};
      method: "connect";
    }
  | {
      data: {};
      method: "disconnect";
    }
  | {
      data: {};
      method: "info";
    }
  | {
      data: {
        req: DeviceManagerRequest;
      };
      method: "device_manager_call";
    }
  | {
      data: {
        req: unknown;
      };
      method: "call";
    };
export type DeviceManagerRequest =
  | {
      data: {
        data: unknown;
        device_id: DeviceId;
        domain: string;
      };
      method: "call";
    }
  | {
      data: {};
      method: "devices";
    };
export type DeviceId =
  | {
      Dfu: number;
    }
  | {
      Serial: number;
    };
export type ProviderManagerResponse =
  | {
      data: null;
      method: "delete";
    }
  | {
      data: WrappedDeviceProviderResponse;
      method: "provider";
    }
  | {
      data: {
        [k: string]: ProviderInfo;
      };
      method: "providers";
    };
export type WrappedDeviceProviderResponse =
  | {
      data: null;
      method: "connect";
    }
  | {
      data: null;
      method: "disconnect";
    }
  | {
      data: ProviderInfo;
      method: "info";
    }
  | {
      data: DeviceManagerResponse;
      method: "device_manager_call";
    }
  | {
      data: unknown;
      method: "call";
    };
export type DeviceManagerResponse =
  | {
      data: unknown;
      method: "call";
    }
  | {
      data: {
        [k: string]: [DeviceId, DeviceInfo, string][];
      };
      method: "devices";
    };
export type DeviceType =
  | ("RoboRIO" | "Unknown")
  | {
      Grapple: GrappleModelId;
    };
export type GrappleModelId = "LaserCan" | "SpiderLan" | "FlexiCAN" | "MitoCANdria";
export type RoboRioDaemonRequest =
  | {
      data: {};
      method: "status";
    }
  | {
      data: {
        use_daemon: boolean;
      };
      method: "set_use_daemon";
    }
  | {
      data: {
        address: string;
      };
      method: "set_address";
    }
  | {
      data: {
        req: CanLogRequest;
      };
      method: "canlog_call";
    };
export type CanLogRequest =
  | {
      data: {
        enabled: boolean;
      };
      method: "set_log_enabled";
    }
  | {
      data: {};
      method: "clear";
    }
  | {
      data: {
        seq: number;
      };
      method: "read_after";
    }
  | {
      data: {
        filters: Filter[];
      };
      method: "set_filters";
    }
  | {
      data: {
        data: number[];
        id: MessageId;
      };
      method: "send_raw";
    };
export type Filter =
  | "GrappleOnly"
  | {
      IdMask: {
        id: MessageId;
        mask: MessageId;
      };
    }
  | {
      IdMaskRaw: {
        id: number;
        mask: number;
      };
    }
  | {
      BodySize: {
        max: number;
        min: number;
      };
    };
export type RoboRioDaemonResponse =
  | {
      data: RoboRIOStatus;
      method: "status";
    }
  | {
      data: null;
      method: "set_use_daemon";
    }
  | {
      data: null;
      method: "set_address";
    }
  | {
      data: CanLogResponse;
      method: "canlog_call";
    };
export type CanLogResponse =
  | {
      data: null;
      method: "set_log_enabled";
    }
  | {
      data: null;
      method: "clear";
    }
  | {
      data: MailboxItem[];
      method: "read_after";
    }
  | {
      data: null;
      method: "set_filters";
    }
  | {
      data: null;
      method: "send_raw";
    };
export type GrappleDeviceMessage =
  | {
      data: GrappleBroadcastMessage;
      type: "Broadcast";
    }
  | {
      data: GrappleFirmwareMessage;
      type: "FirmwareUpdate";
    }
  | {
      data: LaserCanMessage;
      type: "DistanceSensor";
    }
  | {
      data: MitocandriaMessage;
      type: "PowerDistributionModule";
    }
  | {
      data: FlexiCANMessage;
      type: "IOBreakout";
    }
  | {
      data: MiscMessage;
      type: "Misc";
    };
export type GrappleBroadcastMessage = {
  data: GrappleDeviceInfo;
  type: "DeviceInfo";
};
export type GrappleDeviceInfo =
  | {
      type: "EnumerateRequest";
    }
  | {
      data: {
        is_dfu: boolean;
        is_dfu_in_progress: boolean;
        model_id: GrappleModelId;
        name: string;
        serial: number;
        version: string;
      };
      type: "EnumerateResponse";
    }
  | {
      data: {
        serial: number;
      };
      type: "Blink";
    }
  | {
      data: {
        name: string;
        serial: number;
      };
      type: "SetName";
    }
  | {
      data: {
        serial: number;
      };
      type: "CommitConfig";
    }
  | {
      data: {
        new_id: number;
        serial: number;
      };
      type: "SetId";
    }
  | {
      type: "ArbitrationRequest";
    }
  | {
      type: "ArbitrationReject";
    };
export type GrappleFirmwareMessage =
  | {
      data: {
        serial: number;
      };
      type: "StartFieldUpgrade";
    }
  | {
      data: number[];
      type: "UpdatePart";
    }
  | {
      type: "UpdatePartAck";
    }
  | {
      type: "UpdateDone";
    }
  | {
      data: RequestFor_UpdatePartV2PayloadAnd_ResultOf_NullOr_GrappleError;
      type: "UpdatePartV2";
    }
  | {
      data: RequestFor_NullAnd_ResultOf_FlashParametersOr_GrappleError;
      type: "GetFlashParameters";
    };
export type RequestFor_UpdatePartV2PayloadAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: UpdatePartV2Payload;
      type: "Request";
    };
export type ResultOf_NullOr_GrappleError =
  | {
      Ok: null;
    }
  | {
      Err: GrappleError;
    };
export type GrappleError =
  | {
      data: string;
      type: "ParameterOutOfBounds";
    }
  | {
      data: string;
      type: "FailedAssertion";
    }
  | {
      data: string;
      type: "TimedOut";
    }
  | {
      data: string;
      type: "Generic";
    };
export type RequestFor_NullAnd_ResultOf_FlashParametersOr_GrappleError =
  | {
      data: ResultOf_FlashParametersOr_GrappleError;
      type: "Ack";
    }
  | {
      data: null;
      type: "Request";
    };
export type ResultOf_FlashParametersOr_GrappleError =
  | {
      Ok: FlashParameters;
    }
  | {
      Err: GrappleError;
    };
export type LaserCanMessage =
  | {
      data: LaserCanMeasurement;
      type: "Measurement";
    }
  | {
      data: RequestFor_LaserCanRangingModeAnd_ResultOf_NullOr_GrappleError;
      type: "SetRange";
    }
  | {
      data: RequestFor_LaserCanRoiAnd_ResultOf_NullOr_GrappleError;
      type: "SetRoi";
    }
  | {
      data: RequestFor_LaserCanTimingBudgetAnd_ResultOf_NullOr_GrappleError;
      type: "SetTimingBudget";
    }
  | {
      data: RequestForUint16And_ResultOf_NullOr_GrappleError;
      type: "SetLedThreshold";
    };
export type RequestFor_LaserCanRangingModeAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: LaserCanRangingMode;
      type: "Request";
    };
export type RequestFor_LaserCanRoiAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: LaserCanRoi;
      type: "Request";
    };
export type RequestFor_LaserCanTimingBudgetAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: LaserCanTimingBudget;
      type: "Request";
    };
export type RequestForUint16And_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: number;
      type: "Request";
    };
export type MitocandriaMessage =
  | {
      data: MitocandriaStatusFrame;
      type: "StatusFrame";
    }
  | {
      data: MitocandriaChannelRequest;
      type: "ChannelRequest";
    };
export type MitocandriaChannelRequest =
  | {
      data: RequestFor_MitocandriaSwitchableChannelRequestAnd_ResultOf_NullOr_GrappleError;
      type: "SetSwitchableChannel";
    }
  | {
      data: RequestFor_MitocandriaAdjustableChannelRequestAnd_ResultOf_NullOr_GrappleError;
      type: "SetAdjustableChannel";
    }
  | {
      data: RequestFor_MitocandriaAdjustableChannelCalibrationRequestAnd_ResultOf_NullOr_GrappleError;
      type: "CalibrateAdjChannel";
    }
  | {
      data: RequestFor_NullAnd_ResultOf_NullOr_GrappleError;
      type: "StartAutoCalibrate";
    };
export type RequestFor_MitocandriaSwitchableChannelRequestAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: MitocandriaSwitchableChannelRequest;
      type: "Request";
    };
export type RequestFor_MitocandriaAdjustableChannelRequestAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: MitocandriaAdjustableChannelRequest;
      type: "Request";
    };
export type RequestFor_MitocandriaAdjustableChannelCalibrationRequestAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: MitocandriaAdjustableChannelCalibrationRequest;
      type: "Request";
    };
export type RequestFor_NullAnd_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: null;
      type: "Request";
    };
export type FlexiCANMessage = {
  data: BridgeMessages;
  type: "Bridge";
};
export type BridgeMessages =
  | {
      data: RequestForUint8And_ResultOf_StringOr_GrappleError;
      type: "GetChannelName";
    }
  | {
      data: RequestForUint8And_ResultOf_NullOr_GrappleError;
      type: "StartBridge";
    }
  | {
      data: RequestForUint8And_ResultOf_NullOr_GrappleError;
      type: "StopBridge";
    }
  | {
      data: EncapsulatedMesssage;
      type: "BridgeMessage";
    };
export type RequestForUint8And_ResultOf_StringOr_GrappleError =
  | {
      data: ResultOf_StringOr_GrappleError;
      type: "Ack";
    }
  | {
      data: number;
      type: "Request";
    };
export type ResultOf_StringOr_GrappleError =
  | {
      Ok: string;
    }
  | {
      Err: GrappleError;
    };
export type RequestForUint8And_ResultOf_NullOr_GrappleError =
  | {
      data: ResultOf_NullOr_GrappleError;
      type: "Ack";
    }
  | {
      data: number;
      type: "Request";
    };
export type MiscMessage =
  | {
      data: number[];
      type: "MiscMessage";
    }
  | {
      data: JMSMessage;
      type: "JMS";
    };
export type JMSMessage =
  | {
      data: JMSElectronicsStatus;
      type: "Status";
    }
  | {
      data: JMSRole;
      type: "SetRole";
    }
  | {
      data: JMSElectronicsUpdate;
      type: "Update";
    }
  | {
      type: "Blink";
    };
export type JMSCardStatus =
  | "Lighting"
  | {
      /**
       * @minItems 8
       * @maxItems 8
       */
      IO: [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean];
    };
export type JMSRole =
  | ("ScoringTable" | "TimerRed" | "TimerBlue")
  | {
      Red: number;
    }
  | {
      Blue: number;
    };
export type JMSCardUpdate =
  | {
      /**
       * @minItems 0
       * @maxItems 0
       */
      IO: [];
    }
  | {
      Lighting: {
        back_background: Pattern;
        background: Pattern;
        bottom_bar: Pattern;
        text: string;
        text_back: string;
        text_back_colour: Colour;
        text_colour: Colour;
        top_bar: Pattern;
      };
    };
export type Pattern =
  | "Blank"
  | {
      Solid: Colour;
    }
  | {
      /**
       * @minItems 2
       * @maxItems 2
       */
      DiagonalStripes: [Colour, Colour];
    }
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      FillLeft: [Colour, Colour, number];
    }
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      FillRight: [Colour, Colour, number];
    };

export interface MegaSchema {
  firmware_req: FirmwareUpgradeDeviceRequest;
  firmware_rsp: FirmwareUpgradeDeviceResponse;
  flexican_req: FlexiCanRequest;
  flexican_rsp: FlexiCanResponse;
  lasercan_req: LaserCanRequest;
  lasercan_rsp: LaserCanResponse;
  light_release_response: LightReleaseResponse;
  mitocandria_req: MitocandriaRequest;
  mitocandria_rsp: MitocandriaResponse;
  old_version_req: OldVersionDeviceRequest;
  old_version_rsp: OldVersionDeviceResponse;
  provider_manager_req: ProviderManagerRequest;
  provider_manager_rsp: ProviderManagerResponse;
  roborio_req: RoboRioDaemonRequest;
  roborio_rsp: RoboRioDaemonResponse;
}
export interface FlexiCanStatus {}
export interface LaserCanRoi {
  h: number;
  w: number;
  x: number;
  y: number;
}
export interface LaserCanStatus {
  last_update?: LaserCanMeasurement | null;
}
export interface LaserCanMeasurement {
  ambient: number;
  budget: LaserCanTimingBudget;
  distance_mm: number;
  mode: LaserCanRangingMode;
  roi: LaserCanRoi;
  status: number;
}
export interface LightReleaseResponse {
  html_url: string;
  name: string;
  published_at: string;
  tag_name: string;
}
export interface MitocandriaSwitchableChannelRequest {
  channel: number;
  enabled: boolean;
}
export interface MitocandriaAdjustableChannelRequest {
  channel: number;
  voltage: number;
}
export interface MitocandriaStatus {
  last_update?: MitocandriaStatusFrame | null;
}
export interface MitocandriaStatusFrame {
  /**
   * @minItems 5
   * @maxItems 5
   */
  channels: [
    MitocandriaChannelStatus,
    MitocandriaChannelStatus,
    MitocandriaChannelStatus,
    MitocandriaChannelStatus,
    MitocandriaChannelStatus
  ];
}
export interface ProviderInfo {
  address: string;
  connected: boolean;
  description: string;
  ty: string;
}
export interface DeviceInfo {
  device_id?: number | null;
  device_type: DeviceType;
  firmware_version?: string | null;
  is_dfu: boolean;
  is_dfu_in_progress: boolean;
  name?: string | null;
  serial?: number | null;
}
export interface MessageId {
  api_class: number;
  api_index: number;
  device_id: number;
  device_type: number;
  manufacturer: number;
}
export interface RoboRIOStatus {
  using_daemon: boolean;
}
export interface MailboxItem {
  grpl_defrag?: GrappleDeviceMessage | null;
  raw: BridgedCANMessage;
  seq: number;
}
export interface UpdatePartV2Payload {
  offset: number;
  payload: number[];
}
export interface FlashParameters {
  align: number;
  flash_compat_version: number;
  payload_len: number;
}
export interface MitocandriaAdjustableChannelCalibrationRequest {
  offset_mv: number;
}
export interface EncapsulatedMesssage {
  channel: number;
  data: number[];
  id: MessageId;
  timestamp: number;
}
export interface JMSElectronicsStatus {
  /**
   * @minItems 2
   * @maxItems 2
   */
  cards: [JMSCardStatus, JMSCardStatus];
  role: JMSRole;
}
export interface JMSElectronicsUpdate {
  card: number;
  update: JMSCardUpdate;
}
export interface Colour {
  blue: number;
  green: number;
  red: number;
}
export interface BridgedCANMessage {
  data: number[];
  id: MessageId;
  timestamp: number;
}
